### ISSUE TITLE
cmd-shift-enter doesn't strip whitespace

### ISSUE THREAD

**Issue by noseglid** [iconara/blackspace#1]
When on a line with only white-spaces, it correctly removes them if I press enter. If I want to add a new line above the current line, it doesn't work however. 
![blackspace](https://cloud.githubusercontent.com/assets/933880/5441424/88c8c7dc-8490-11e4-9a64-49ef681d2aa8.gif)

**Comment by iconara** [comment]
Good catch, I'll have a look and see if I can fix that.

**Comment by noseglid** [comment]
Same problem if I press 'cmd-enter' (on mac) which should theoretically work the same way as just 'enter'.

**Comment by masv** [comment]
I have made a pull request that should fix the issue of 'cmd-enter' (and the other default mappings for Atom's `newline` and `newline-below` commands). Also looking into ways to fix `newline-above`.

**Comment by iconara** [comment]
Fixed by #3 (v1.1.0)
